public inherited sharing class DLT_CorporateTrackingConstants {
    public static final Id RT_ID_BE_CONTINENT = Schema.SObjectType.Corp_Tracking_Type_and_Code__c.getRecordTypeInfosByDeveloperName().get('GND_Belgium_Continent').getRecordTypeId();
    public static final Id RT_ID_BE_LONDON = Schema.SObjectType.Corp_Tracking_Type_and_Code__c.getRecordTypeInfosByDeveloperName().get('GND_Belgium_London').getRecordTypeId();
    public static final Id RT_ID_NL_CONTINENT = Schema.SObjectType.Corp_Tracking_Type_and_Code__c.getRecordTypeInfosByDeveloperName().get('GND_The_Netherlands_Continent').getRecordTypeId();
    public static final Id RT_ID_NL_LONDON = Schema.SObjectType.Corp_Tracking_Type_and_Code__c.getRecordTypeInfosByDeveloperName().get('GND_The_Netherlands_London').getRecordTypeId();
}