public without sharing class DLT_InvoiceConstants {
    
    public static final String STATUS_CONFIRMED = 'Confirmed';
    public static final String STATUS_PROFORMA = 'Pro Forma';
    public static final String STATUS_CANCELLED = 'Cancelled';

    public static final String NUMBER_PREFIX = '-INV-';

    public static final String EXCEPTION_INVALID_NUMBER = 'Invalid Order Number or No Status on Invoice';
}