public inherited sharing class DLT_SubscriptionConstants {

    public static final String STATUS_ACTIVE = 'Active';
    public static final String STATUS_INACTIVE = 'Inactive';
    public static final String STATUS_PENDING_PAYMENT = 'Pending Payment';
    public static final String STATUS_NOT_STARTED = 'Not Started';
    public static final String STATUS_CANCELED = 'Cancelled';
    public static final String STATUS_EXPIRED = 'Expired';
}